[tools]
bun = "1.3.9"

# Internal
"go:github.com/project-init/devex/cmd/release" = "latest"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true
npm.bun = true

# Setup

[tasks.setup]
run = "bun install"

# Build

[tasks.build]
depends = ["setup"]
run = "bun run build"

# Tests

[tasks.test]
depends = [
    "unit-test"
]

[tasks.unit-test]
depends = ["setup"]
run = "bun run test"

# Linting

[tasks.format]
depends = ["format-*"]

[tasks.format-prettier-sync]
depends = ["setup"]
run = "sh ./scripts/sync-prettier-config.sh"

[tasks.format-prettier]
depends = ["format-prettier-sync"]
run = "bun run format"

[tasks.lint]
depends = ["lint-*"]

[tasks.lint-prettier]
depends = ["format-prettier-sync"]
run = "bun run lint"

# Dependencies

[tasks.update-dependencies]
run = "bun update"
depends_post = ["setup"]
