[tools]
bun = "1.3.9"
node = "25.7.0"
prettier = "3.8.1"

# Internal
"go:github.com/project-init/devex/cmd/release" = "latest"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true
npm.bun = true

# Setup

[tasks.setup]
run = "bun install"

# Build

[tasks.build]
depends = ["setup"]
run = "bun run build"

# Tests

[tasks.test]
depends = [
    "unit-test"
]

[tasks.unit-test]
depends = ["setup"]
run = "bun run test"

# Linting

[tasks.format]
depends = [
    "format-prettier",
    "format-bun",
]

[tasks.format-prettier-sync]
run = "sh ./scripts/sync-prettier-config.sh"

[tasks.format-prettier]
depends = ["format-prettier-sync"]
run = "prettier --config ./prettier.config.json --ignore-path ./.prettierignore --write \"**/*.{md,yml,yaml}\""

[tasks.format-bun]
depends = ["setup"]
run = "bun run format"

[tasks.lint]
depends = ["lint-prettier"]

[tasks.lint-prettier]
depends = ["format-prettier-sync"]
run = "prettier --config ./prettier.config.json --ignore-path ./.prettierignore --check \"**/*.{md,yml,yaml}\""

# Dependencies

[tasks.update-dependencies]
run = "bun update"
depends_post = ["setup"]
